<a href="https://colab.research.google.com/github/ArnyWu/-Preview-AI-/blob/main/7113029049PyTorch%E5%9F%BA%E7%A4%8E%E7%9F%A5%E8%AD%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



torch tensor教學筆記



In [1]:
import torch

In [5]:
z = torch.Tensor(4,5) #維度尺寸(二維)
z

tensor([[6.7014e-10, 6.8684e-07, 2.1707e-18, 1.6678e+19, 7.0976e+22],
        [2.1715e-18, 4.2330e+21, 1.6534e+19, 1.1625e+27, 1.4580e-19],
        [7.1856e+22, 4.3605e+27, 1.5766e-19, 7.1856e+22, 4.3605e+27],
        [1.4580e-19, 1.8179e+31, 1.8524e+28, 2.1715e-18, 2.1860e-04]])



> 以多層list來表現



In [6]:
z.dtype

torch.float32

##  1. 浮點數tensor



In [7]:
a = torch.FloatTensor(4,5)
b = torch.FloatTensor([[2,3],[4,5]])
a

tensor([[9.4708e-25, 4.5209e-41, 7.4952e+03, 3.3256e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
b

tensor([[2., 3.],
        [4., 5.]])

In [9]:
a.dtype

torch.float32

In [10]:
b.dtype

torch.float32

## 2. 整數tensor

In [11]:
a = torch.IntTensor(4,5)
b = torch.IntTensor([[2,3],[4,5]])
a

tensor([[1015451160,      32261, 1015451160,      32261,          0],
        [         0,          3,          0,  902968832,          1],
        [         9,      32261,   83545240, 1479713700,         97],
        [         0, 1172844240,      23732, 1170650192,      23732]],
       dtype=torch.int32)

In [12]:
b

tensor([[2, 3],
        [4, 5]], dtype=torch.int32)

In [14]:
y = a+z
y

tensor([[1.0155e+09, 3.2261e+04, 1.0155e+09, 1.6678e+19, 7.0976e+22],
        [2.1715e-18, 4.2330e+21, 1.6534e+19, 1.1625e+27, 1.0000e+00],
        [7.1856e+22, 4.3605e+27, 8.3545e+07, 7.1856e+22, 4.3605e+27],
        [1.4580e-19, 1.8179e+31, 1.8524e+28, 1.1707e+09, 2.3732e+04]])

In [15]:
y.dtype

torch.float32



> 自動轉換成精度較高的



In [16]:
torch.add(z,a) #不用變數裝結果

tensor([[1.0155e+09, 3.2261e+04, 1.0155e+09, 1.6678e+19, 7.0976e+22],
        [2.1715e-18, 4.2330e+21, 1.6534e+19, 1.1625e+27, 1.0000e+00],
        [7.1856e+22, 4.3605e+27, 8.3545e+07, 7.1856e+22, 4.3605e+27],
        [1.4580e-19, 1.8179e+31, 1.8524e+28, 1.1707e+09, 2.3732e+04]])

In [17]:
a = torch.rand(4,5)
a

tensor([[0.0115, 0.2584, 0.2045, 0.2770, 0.5726],
        [0.9515, 0.6818, 0.2742, 0.3560, 0.3468],
        [0.5343, 0.8591, 0.1020, 0.5037, 0.4786],
        [0.8747, 0.1235, 0.2039, 0.6848, 0.4876]])

In [18]:
a.dtype

torch.float32

### 3. numpy ↔️ tensor

將tensor內值取出作為array

In [22]:
b = a.numpy()
b

array([[0.01147407, 0.25844586, 0.20445067, 0.27700216, 0.5725746 ],
       [0.9515092 , 0.6817879 , 0.27424294, 0.3560055 , 0.34679264],
       [0.5342997 , 0.85905504, 0.1019913 , 0.5036806 , 0.47862303],
       [0.8746893 , 0.1235171 , 0.20392609, 0.6848043 , 0.487561  ]],
      dtype=float32)

將 numpy 轉為 tensor

In [23]:
import numpy as np

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
a

array([1., 1., 1., 1., 1.])

In [26]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)



> 生成出來的會是float64，與預設float32不同



## 3. 操作陣列

In [27]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [28]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



> from_numpy 是 共享記憶體



## 4. 型別轉換

In [29]:
c = b + torch.FloatTensor([1,2,3,4,5])
c

tensor([3., 4., 5., 6., 7.], dtype=torch.float64)

In [31]:
c = c.float() #轉回float32
c.dtype

torch.float32

In [32]:
c = c.double() #轉回float64
c.dtype

torch.float64

In [33]:
c = c.int() #轉int32
c.dtype

torch.int32

## 5. torch尺寸變化

In [36]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [37]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

消掉多餘維度

In [38]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [39]:
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

指定消掉的維度

In [40]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [41]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [42]:
y = torch.squeeze(y,2)
y.size()

torch.Size([2, 2, 2])

## 6. 數值設定

絕對值

In [43]:
torch.abs(torch.FloatTensor([-1,-2,-3]))

tensor([1., 2., 3.])

有正有負

In [44]:
a = torch.randn(4)
a

tensor([ 0.9406, -1.6453, -0.4048, -1.5210])

In [45]:
b = torch.add(a, 20)
b

tensor([20.9406, 18.3547, 19.5952, 18.4790])

In [46]:
c = torch.mul(a, 0.1)
c

tensor([ 0.0941, -0.1645, -0.0405, -0.1521])

In [47]:
d = torch.mul(a,b)
d

tensor([ 19.6978, -30.1989,  -7.9313, -28.1067])

矩陣乘法

In [48]:
x = torch.rand(2,3)
y = torch.rand(3,2)
x

tensor([[0.6726, 0.7730, 0.6075],
        [0.3401, 0.3616, 0.3207]])

In [49]:
y

tensor([[0.5975, 0.7504],
        [0.5481, 0.4477],
        [0.9324, 0.6287]])

有順序性

In [50]:
d = torch.matmul(x,y)
d

tensor([[1.3920, 1.2327],
        [0.7005, 0.6188]])

In [51]:
d = torch.matmul(y,x)
d

tensor([[0.6571, 0.7332, 0.6037],
        [0.5209, 0.5855, 0.4766],
        [0.8410, 0.9481, 0.7681]])

In [52]:
y.size()

torch.Size([3, 2])

## 7. 平均

In [53]:
y.mean()

tensor(0.6508)

In [55]:
k = y.mean()
k.data.dtype

torch.float32

In [57]:
torch.mean(y)

tensor(0.6508)

Row 的平均

```
 tensor([[0.5975⬇️, 0.7504]⬇️,       
     [0.5481 , 0.4477],
     [0.9324 , 0.6287]])
```


In [58]:
torch.mean(y,0)

tensor([0.6927, 0.6089])

column 的平均


```
 tensor([[0.5975➡️, 0.7504],       
     [0.5481➡️ , 0.4477],
     [0.9324➡️ , 0.6287]])
```



In [59]:
torch.mean(y,1)

tensor([0.6739, 0.4979, 0.7806])

## 8. 比較

In [61]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[1,1],[4,4]])
x

tensor([[1., 2.],
        [3., 4.]])

In [62]:
y

tensor([[1., 1.],
        [4., 4.]])

In [64]:
torch.eq(x,y) #比較裡面的值是否相同

tensor([[ True, False],
        [False,  True]])

In [68]:
torch.equal(y,y) #比較矩陣是否相同

True

In [69]:
torch.ge(x,y) #>=大於等於

tensor([[ True,  True],
        [False,  True]])

In [70]:
torch.le(x,y) #<=小於等於

tensor([[ True, False],
        [ True,  True]])

In [71]:
torch.gt(x,y) #>大於

tensor([[False,  True],
        [False, False]])

In [72]:
torch.lt(x,y) #<小於

tensor([[False, False],
        [ True, False]])